server:
  port: 8080
  servlet:
    context-path: /pezsoft/v1
    session:
      timeout: 21600s
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=PEZSOFT_DB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.SQLServerDialect